spring.application.name=weather_application
spring.datasource.url=jdbc:postgresql://localhost:5432/weather-db
spring.datasource.username=postgres
spring.datasource.password=7008


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# OpenWeather
openweather.api-key=${OPENWEATHER_API_KEY}

openweather.weather-base-url=https://api.openweathermap.org/data/2.5
openweather.geocoding-base-url=http://api.openweathermap.org/geo/1.0

# RestClient timeouts
openweather.connect-timeout=5s
openweather.read-timeout=10s


spring.cache.type=caffeine
spring.cache.cache-names=weather
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRGb3JMb2NhbExlYXJuaW5n
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

logging.level.com.kpaatmik.weather_application=DEBUG